/*Get 5 numbers from the user and arrange in descending order and print the same.*/
#include <stdio.h>
int main()
{
    int a[5],i,c,b,t;
    printf("Enter the number:");
    for(i=0;i<5;i++)
    {
        scanf("%d",&a[i]);
    }
    c=a[0];
    b=0;//a[0]
    for(i=0;i<5;i++)
    {
        if(a[i]>c)
        {
            c=a[i];
            b=i;
        }
        if(i==4)
        {
            t=a[0];
            a[0]=c;
            a[b]=t;
        }
    }
    c=a[1];
    b=1;//a[1]
    for(i=1;i<5;i++)
    {
        if(a[i]>c)
        {
            c=a[i];
            b=i;
        }
        if(i==4)
        {
            t=a[1];
            a[1]=c;
            a[b]=t;
        }
    }
    c=a[2];
    b=2;//a[2]
    for(i=2;i<5;i++)
    {
        if(a[i]>c)
        {
            c=a[i];
            b=i;
        }
        if(i==4)
        {
            t=a[2];
            a[2]=c;
            a[b]=t;
        }
    }
    c=a[3];
    b=3;//a[3]
    for(i=3;i<5;i++)
    {
        if(a[i]>c)
        {
            c=a[i];
            b=i;
        }
        if(i==4)
        {
            t=a[3];
            a[3]=c;
            a[b]=t;
        }
    }
    c=a[4];
    b=4;//a[4]
    for(i=4;i<5;i++)
    {
        if(a[i]>c)
        {
            c=a[i];
            b=i;
        }
        if(i==4)
        {
            t=a[4];
            a[4]=c;
            a[b]=t;
        }
    }
    for(i=0;i<5;i++)
    {
        printf("%d",a[i]);
    }
}